### ISSUE TITLE
Incomplete docs for "Skipping Resource Actions"

### ISSUE THREAD

**Issue by nachtwerk** [gobuffalo/gobuffalo#413] opened 2018-12-07 08:22 UTC
The section which explains how to skip middleware for a particular function of a resource, is missing the explanation on how to set this up.
https://gobuffalo.io/en/docs/middleware#skipping-resource-actions

As far as I can tell from reading the docs, the solution is to split out each function of the resource and let them use the middleware that is required.
https://godoc.org/github.com/gobuffalo/buffalo#App.Resource

Is this the correct way or is there a more concise way to go about this? Can the docs be updated to reflect this?

**Comment by lukasschlueter** [comment] 2018-12-07 09:21
The documentation is actually present in https://github.com/gobuffalo/gobuffalo/blob/master/templates/docs/middleware/_skipping_resource.md
It also includes how to skip middleware for resources.

The problem is related to a general markdown and template helper issue.

See #412 for more information on this

**Comment by lukasschlueter** [comment] 2019-01-18 23:08
Closed in #417

**Closed by lukasschlueter** 2019-01-18 23:08 UTC
